name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET 10
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      # 3️⃣ Restore dependencies
      - name: Restore
        run: dotnet restore

      # 4️⃣ Build benchmarks project
      - name: Build benchmarks
        run: dotnet build benchmarks/DotNetDev.AspNetCore.Http.Benchmarks -c Release

      # 5️⃣ Run benchmarks non-interactively
      - name: Run benchmarks
        run: dotnet run -c Release --project benchmarks/DotNetDev.AspNetCore.Http.Benchmarks -- --filter "*" --exporters html,json,csv

      # 6️⃣ Upload benchmark JSON/CSV/HTML artifacts
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmarks/results/*  # includes all JSON, CSV, HTML

  deploy-pages:
    needs: benchmark
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository (needed for Pages deployment)
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3️⃣ Upload the benchmark results folder (HTML + JSON + CSV)
      - name: Upload benchmark dashboard
        uses: actions/upload-pages-artifact@v3
        with:
          path: benchmarks/results  # deploy the entire folder

      # 4️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
