name: Deploy Benchmark Pages

on:
  workflow_run:
    workflows: ["Benchmarks"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout gh-benchmark-pages branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-benchmark-pages
          persist-credentials: false

      # 2️⃣ Download benchmark artifacts from previous workflow
      - name: Download benchmark artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: benchmark-results
          path: benchmarks/results

      # 3️⃣ Copy results into new timestamped history folder
      - name: Save historical benchmark results
        run: |
          timestamp=$(date -u +"%Y%m%d-%H%M%S")
          mkdir -p src/history/$timestamp/benchmark-results
          cp -r benchmarks/results/* src/history/$timestamp/benchmark-results/
          echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV

      # 4️⃣ Generate index.html from template with Owl Carousel slides
      - name: Generate dashboard from template
        run: |
          SLIDES=""
          INDEX=1
          for dir in src/history/*; do
            ts=$(basename "$dir")
            results_dir="$dir/benchmark-results"
            for report_file in "$results_dir"/*.htm*; do
              if [ -f "$report_file" ]; then
                # Use relative path from index.html to file
                REL_PATH="history/$ts/benchmark-results/$(basename "$report_file")"
                CARD="<div class=\"card\">
                        <div class=\"timestamp\">$ts</div>
                        <div class=\"report-name\">Report #$INDEX</div>
                        <a href=\"#\" class=\"view-report\" onclick=\"openModalFromFile('$REL_PATH')\">View Report</a>
                      </div>"
                SLIDES="$SLIDES$CARD"
                INDEX=$((INDEX+1))
              fi
            done
          done
      
          # Wrap 15 cards per slide (3 rows x 5 columns)
          FINAL_HTML=""
          CARDS_PER_SLIDE=15
          CARD_ARRAY=()
          # Split SLIDES into individual cards
          while [[ $SLIDES =~ (<div class=\"card\">.*?</div>) ]]; do
              CARD_ARRAY+=("${BASH_REMATCH[1]}")
              SLIDES=${SLIDES#*"${BASH_REMATCH[1]}"}
          done
          
          TOTAL_CARDS=${#CARD_ARRAY[@]}
          i=0
          while [ $i -lt $TOTAL_CARDS ]; do
              SLIDE=""
              for ((j=0; j<$CARDS_PER_SLIDE && i<TOTAL_CARDS; j++, i++)); do
                  SLIDE="$SLIDE${CARD_ARRAY[$i]}"
              done
              FINAL_HTML="$FINAL_HTML<div class='slide-grid'>$SLIDE</div>"
          done
      
          # Inject into template
          TEMPLATE_FILE="src/index.template.html"
          INDEX_FILE="src/index.html"
          awk -v slides="$FINAL_HTML" '{gsub(/<!--SLIDES-->/,slides); print}' "$TEMPLATE_FILE" > "$INDEX_FILE"

      # 5️⃣ Commit history + index.html
      - name: Commit historical results
        run: |
          git config user.name "github-action-benchmark"
          git config user.email "github@users.noreply.github.com"
          git add src/history src/index.html
          git commit -m "Add benchmark results for ${{ env.TIMESTAMP }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-benchmark-pages

      # 6️⃣ Upload src folder as Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
