name: Deploy Benchmark Pages

on:
  workflow_run:
    workflows: ["Benchmarks"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout gh-benchmark-pages branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-benchmark-pages
          persist-credentials: false

      # 2️⃣ Download benchmark artifacts from previous workflow
      - name: Download benchmark artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: benchmark-results
          path: benchmarks/results

      # 3️⃣ Copy results into new timestamped history folder
      - name: Save historical benchmark results
        run: |
          timestamp=$(date -u +"%Y%m%d-%H%M%S")
          mkdir -p src/history/$timestamp/benchmark-results
          cp -r benchmarks/results/* src/history/$timestamp/benchmark-results/
          echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV

      # 4️⃣ Debug: list what we actually have in history
      - name: List history contents
        run: |
          echo "History folder after adding new results:"
          ls -R src/history || true

      # 5️⃣ Generate index.html from carousel template
      - name: Generate dashboard from template
        run: |
          TEMPLATE_FILE="src/index.template.html"
          OUTPUT_FILE="src/index.html"
      
          cp "$TEMPLATE_FILE" "$OUTPUT_FILE"
      
          slides=""
          index=1
      
          # Loop over historical folders
          for dir in src/history/*; do
              ts=$(basename "$dir")
              slide="<div class='slide-grid'>"
      
              # Loop over each report in the timestamp folder
              for report_html in "$dir"/benchmark-results/*.html; do
                  report_name="Report #$index"
                  report_link="history/$ts/benchmark-results/$(basename "$report_html")"
      
                  card="<div class='card'>
                          <div class='timestamp'>$ts</div>
                          <div class='report-name'>$report_name</div>
                          <a href='$report_link' class='view-report'>View Report</a>
                        </div>"
      
                  slide="$slide$card"
                  index=$((index+1))
              done
      
              slide="$slide</div>"
              slides="$slides$slide"
          done
      
          # Safe replacement of <!--SLIDES--> placeholder using awk
          awk -v slides="$slides" '{gsub("<!--SLIDES-->", slides); print}' "$TEMPLATE_FILE" > "$OUTPUT_FILE"

      # 6️⃣ Commit historical results + index.html
      - name: Commit historical results
        run: |
          git config user.name "github-action-benchmark"
          git config user.email "github@users.noreply.github.com"
          git add src/history src/index.html
          git status
          git commit -m "Add benchmark results for ${{ env.TIMESTAMP }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-benchmark-pages

      # 7️⃣ Upload src folder as Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src

      # 8️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

