name: Deploy Benchmark Pages

on:
  workflow_run:
    workflows: ["Benchmarks"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout gh-benchmark-pages branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-benchmark-pages
          persist-credentials: false

      # 2️⃣ Download benchmark artifacts
      - name: Download benchmark artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: benchmark-results
          path: benchmarks/results

      # 3️⃣ Save historical results
      - name: Save historical benchmark results
        run: |
          timestamp=$(date -u +"%Y%m%d-%H%M%S")
          mkdir -p src/history/$timestamp/benchmark-results
          cp -r benchmarks/results/* src/history/$timestamp/benchmark-results/
          echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV

      # 4️⃣ List history contents
      - name: List history contents
        run: |
          echo "History folder after adding new results:"
          ls -R src/history || true

      # 5️⃣ Generate dashboard from template
      - name: Generate dashboard from template
        run: |
          SLIDES=""
          INDEX=1
          for dir in src/history/*; do
            ts=$(basename "$dir")
            results_dir="$dir/benchmark-results"
            for report_file in "$results_dir"/*.htm*; do
              if [ -f "$report_file" ]; then
                TABLE=$(grep -Poz "(?s)<table.*?>.*?</table>" "$report_file" | tr -d '\n')
                TABLE_ESCAPED=$(echo "$TABLE" | sed 's/`/\\`/g')
                CARD="<div class=\"card\">
                        <div class=\"timestamp\">$ts</div>
                        <div class=\"report-name\">Report #$INDEX</div>
                        <a href=\"#\" class=\"view-report\" onclick=\"openModal(\`$TABLE_ESCAPED\`)\">View Report</a>
                      </div>"
                SLIDES="$SLIDES$CARD"
                INDEX=$((INDEX+1))
              fi
            done
          done

          # Wrap 15 cards per slide (3x5 grid)
          FINAL_HTML=""
          total=$(echo "$SLIDES" | grep -o "<div class=\"card\">" | wc -l)
          for i in $(seq 0 15 $total); do
            SLIDE=$(echo "$SLIDES" | sed -n "$((i+1)),$((i+15))p")
            FINAL_HTML="$FINAL_HTML<div class='slide-grid'>$SLIDE</div>"
          done

          sed "s|<!--SLIDES-->|$FINAL_HTML|" src/index.template.html > src/index.html

      # 6️⃣ Commit changes
      - name: Commit historical results
        run: |
          git config user.name "github-action-benchmark"
          git config user.email "github@users.noreply.github.com"
          git add src/history src/index.html
          git commit -m "Add benchmark results for ${{ env.TIMESTAMP }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-benchmark-pages

      # 7️⃣ Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src

      # 8️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

