name: Deploy Benchmark Pages

on:
  workflow_run:
    workflows: ["Benchmarks"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository (gh-pages branch)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-benchmark-pages
          persist-credentials: false

      # 2️⃣ Download benchmark artifacts from previous workflow
      - name: Download benchmark artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          path: benchmarks/results

      # 3️⃣ Prepare Pages content
      - name: Prepare Pages content
        run: |
          git fetch origin gh-benchmark-pages
          git checkout gh-benchmark-pages
      
          timestamp=$(date -u +"%Y%m%d-%H%M%S")
          mkdir -p src/history/$timestamp
          cp -r benchmarks/results/* src/history/$timestamp/
      
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add src/history
          git commit -m "Add benchmark results for $timestamp" || echo "Nothing to commit"
      
          # Set authenticated remote for push
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin gh-benchmark-pages
      
          mkdir -p pages
          cp src/index.html pages/
          mkdir -p pages/history
          cp -r src/history/* pages/history/

      # 4️⃣ Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
