name: Deploy Benchmark Pages

on:
  workflow_run:
    workflows: ["Benchmarks"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository (gh-pages branch)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: false

      # 2️⃣ Download benchmark artifacts from previous workflow
      - name: Download benchmark artifacts
        uses: actions/download-artifact@v4
        with:
          name: benchmark-results
          path: benchmarks/results

      # 3️⃣ Prepare Pages content
      - name: Prepare Pages content
        run: |
          mkdir -p pages
          cp -r benchmarks/results/* pages/

      # 4️⃣ Upload content to Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
