name: Deploy Benchmark Pages

on:
  workflow_run:
    workflows: ["Benchmarks"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout gh-benchmark-pages branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-benchmark-pages
          persist-credentials: false

      # 2️⃣ Download benchmark artifacts from previous workflow
      - name: Download benchmark artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: benchmark-results
          path: benchmarks/results

      # 3️⃣ Copy results to historical folder
      - name: Save historical benchmark results
        run: |
          timestamp=$(date -u +"%Y%m%d-%H%M%S")
          mkdir -p src/history/$timestamp
          cp -r benchmarks/results/* src/history/$timestamp/

      # 4️⃣ Generate index.html listing all historical runs
      - name: Generate Pages dashboard
        run: |
          mkdir -p pages
          echo "<h1>Benchmark Dashboard</h1>" > pages/index.html
          echo "<h2>Historical benchmark results:</h2><ul>" >> pages/index.html
          for dir in src/history/*; do
              ts=$(basename "$dir")
              html_file="$dir/benchmark-results/DotNetDev.AspNetCore.Http.Benchmarks.Benchmarks-report.html"
              if [ -f "$html_file" ]; then
                  echo "<li><a href='$html_file'>$ts</a></li>" >> pages/index.html
              fi
          done
          echo "</ul>" >> pages/index.html

      # 5️⃣ Commit historical results and dashboard back to gh-benchmark-pages
      - name: Commit historical results
        run: |
          git config user.name "github-action-benchmark"
          git config user.email "github@users.noreply.github.com"
          git add src/history pages/index.html
          git commit -m "Add benchmark results for $timestamp" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-benchmark-pages

      # 6️⃣ Upload Pages folder to GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      # 7️⃣ Deploy Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
